### Test Root Endpoint
GET http://localhost:3000/
Content-Type: application/json

### Test Contacts Endpoint
GET http://localhost:3000/contacts
Content-Type: application/json


### Test Contacts by User ID 
GET http://localhost:3000/contacts/6673a4099fd578effb457226 HTTP/1.1
Content-Type: application/json

###Create a New Contact
POST http://localhost:3000/contacts
Content-Type: application/json

{
    "firstName": "Irineu",
    "lastName": "Junior",
    "email": "irineu.jr@example.com",
    "favoriteColor": "Blue",
    "birthday": "1995-06-18"
}

###Update a Contact by User ID
PUT http://localhost:3000/contacts/6673a4099fd578effb457226 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Sarah",
    "lastName": "Winter",
    "email": "sarah.winter@gmail.com",
    "favoriteColor": "Orange",
    "birthday": "1999-04-08"
}

###Delete a Contact by User ID
DELETE  http://localhost:3000/contacts/6677a80836b0beb3272225d9 HTTP/1.1
Content-Type: application/json


### PRODUCTION DETAILS

### Test Root Endpoint
GET https://api-project-1-nbqj.onrender.com/
Content-Type: application/json

### Test Contacts Endpoint
GET https://api-project-1-nbqj.onrender.com/contacts
Content-Type: application/json


### Test Contacts by User ID 
GET https://api-project-1-nbqj.onrender.com/contacts/6673a3d59fd578effb457225
Content-Type: application/json